version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static:/static
    restart: always
    ports:
      - "8080:8080"
    networks:
      - web_nw
    depends_on:
      - db
  db:
    image: postgres:10
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    env_file: .env
    networks:
      - web_nw


volumes:
  postgres:
    external: true
  static:
    external: true
networks:
  web_nw:
    external: true