# Generated by Django 4.1.7 on 2023-05-23 08:49

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255, null=True, unique=True)),
                ('last_name', models.CharField(max_length=255, null=True, unique=True)),
                ('national_code', models.BigIntegerField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moadiusername', models.CharField(max_length=255)),
                ('privatekey', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxid', models.CharField(max_length=255, null=True)),
                ('indatim', models.CharField(max_length=255, null=True)),
                ('indati2m', models.CharField(max_length=255, null=True)),
                ('inno', models.CharField(max_length=255, null=True)),
                ('irtaxid', models.CharField(max_length=255, null=True)),
                ('inty', models.PositiveIntegerField(null=True)),
                ('inp', models.PositiveIntegerField(null=True)),
                ('ins', models.PositiveIntegerField(null=True)),
                ('tins', models.IntegerField(null=True)),
                ('tinb', models.IntegerField(null=True)),
                ('tob', models.PositiveIntegerField(null=True)),
                ('sbc', models.IntegerField(null=True)),
                ('bid', models.IntegerField(null=True)),
                ('bpc', models.IntegerField(null=True)),
                ('bbc', models.IntegerField(null=True)),
                ('bpn', models.CharField(max_length=255, null=True)),
                ('ft', models.PositiveIntegerField(null=True)),
                ('scln', models.IntegerField(null=True)),
                ('scc', models.IntegerField(null=True)),
                ('crn', models.IntegerField(null=True)),
                ('sstid', models.IntegerField(null=True)),
                ('sstt', models.CharField(max_length=255, null=True)),
                ('mu', models.PositiveIntegerField(null=True)),
                ('am', models.IntegerField(null=True)),
                ('fee', models.FloatField(null=True)),
                ('cfee', models.FloatField(null=True)),
                ('cut', models.CharField(max_length=255, null=True)),
                ('exr', models.FloatField(null=True)),
                ('iinn', models.IntegerField(null=True)),
                ('acn', models.IntegerField(null=True)),
                ('trmn', models.IntegerField(null=True)),
                ('trn', models.IntegerField(null=True)),
                ('pcn', models.IntegerField(null=True)),
                ('pid', models.IntegerField(null=True)),
                ('pdt', models.CharField(max_length=255, null=True)),
                ('billid', models.IntegerField(null=True)),
                ('prdis', models.FloatField(null=True)),
                ('dis', models.FloatField(null=True)),
                ('adis', models.FloatField(null=True)),
                ('vra', models.FloatField(null=True)),
                ('vam', models.FloatField(null=True)),
                ('odt', models.CharField(max_length=255, null=True)),
                ('odr', models.FloatField(null=True)),
                ('odam', models.FloatField(null=True)),
                ('olt', models.CharField(max_length=255, null=True)),
                ('olr', models.FloatField(null=True)),
                ('olam', models.FloatField(null=True)),
                ('consfee', models.FloatField(null=True)),
                ('spro', models.FloatField(null=True)),
                ('bros', models.FloatField(null=True)),
                ('tcpbs', models.FloatField(null=True)),
                ('cop', models.FloatField(null=True)),
                ('vop', models.FloatField(null=True)),
                ('bsrn', models.IntegerField(null=True)),
                ('setm', models.PositiveIntegerField(null=True)),
                ('tsstam', models.FloatField(null=True)),
                ('tprdis', models.FloatField(null=True)),
                ('tdis', models.FloatField(null=True)),
                ('tadis', models.FloatField(null=True)),
                ('tvam', models.FloatField(null=True)),
                ('todam', models.FloatField(null=True)),
                ('tbill', models.FloatField(null=True)),
                ('tvop', models.FloatField(null=True)),
                ('cap', models.FloatField(null=True)),
                ('insp', models.FloatField(null=True)),
                ('tax17', models.FloatField(null=True)),
                ('dpvb', models.BooleanField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
