# Generated by Django 4.1.7 on 2023-05-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='privatekey',
            field=models.CharField(max_length=25000),
        ),
    ]
