# Generated by Django 4.1.7 on 2023-05-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_dashboard_privatekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='private_key',
            field=models.CharField(max_length=25000, null=True),
        ),
    ]
