# Generated by Django 4.1.7 on 2023-05-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bill_indati2m_alter_bill_indatim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='iinn',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
