# Generated by Django 4.1.7 on 2023-05-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bill_iinn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cdcn',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
