# Generated by Django 4.1.7 on 2023-05-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_bill_cdcn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='inno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='taxid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
