# Generated by Django 4.1.7 on 2023-05-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_bill_inno_alter_bill_taxid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='cdcn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
