# Generated by Django 4.1.7 on 2023-06-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_bill_dpvb_bill_nw_bill_pmt_bill_pv_bill_sscv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cdcd',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
