# Generated by Django 4.1.7 on 2023-06-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_billhistory_delete_dashboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billhistory',
            old_name='refrenceId',
            new_name='refrenceid',
        ),
        migrations.RenameField(
            model_name='billhistory',
            old_name='sendTime',
            new_name='sendtime',
        ),
    ]
