# Generated by Django 4.1.7 on 2023-06-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_refrenceid_billhistory_refrenceid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='refrenceid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='sendtime',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='uuid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='BillHistory',
        ),
    ]
