# Generated by Django 4.1.7 on 2023-06-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_bill_inp_alter_bill_ins_alter_bill_inty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.BigIntegerField(null=True),
        ),
    ]
