# Generated by Django 4.1.7 on 2023-06-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_user_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
