# Generated by Django 4.1.7 on 2023-06-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='inp',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
