# Generated by Django 4.1.7 on 2023-06-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_bill_inp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='ins',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
