# Generated by Django 4.1.7 on 2023-06-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_bill_ins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='odt',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
