# Generated by Django 4.1.7 on 2023-06-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_bill_inp_alter_bill_ins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='inno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='irtaxid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='taxid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
