# Generated by Django 4.1.7 on 2023-06-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_bill_inno_alter_bill_irtaxid_alter_bill_taxid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='inno',
            field=models.CharField(blank=True, default='0038D89F78', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='irtaxid',
            field=models.CharField(blank=True, default='A16G7G04C470038D89F786', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='taxid',
            field=models.CharField(blank=True, default='A16G7G04C470038D89F786', max_length=255, null=True),
        ),
    ]
