# Generated by Django 4.1.7 on 2023-07-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='acn',
            field=models.CharField(blank=True, default='00000000000000', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bid',
            field=models.CharField(blank=True, default='00000000000', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bpc',
            field=models.CharField(blank=True, default='0000000000', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cdcd',
            field=models.BigIntegerField(blank=True, default=10000, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cfee',
            field=models.FloatField(blank=True, default=0.1, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cut',
            field=models.CharField(blank=True, default='XXX', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='exr',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='ft',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='iinn',
            field=models.CharField(blank=True, default='000000000', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='irtaxid',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='mu',
            field=models.CharField(blank=True, default='1628', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='nw',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='pcn',
            field=models.CharField(blank=True, default='0000000000000000', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='pdt',
            field=models.BigIntegerField(blank=True, default=1000000000000, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='pmt',
            field=models.PositiveIntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='scc',
            field=models.CharField(blank=True, default='00000', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sscv',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='ssrv',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tocv',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tonw',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='torv',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='trmn',
            field=models.CharField(blank=True, default='00000000', max_length=255, null=True),
        ),
    ]
