# Generated by Django 4.1.7 on 2023-07-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_bill_acn_alter_bill_bid_alter_bill_bpc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='inno',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='irtaxid',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='taxid',
        ),
    ]
