# Generated by Django 4.1.7 on 2023-07-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_bill_inno_remove_bill_irtaxid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='inno',
            field=models.CharField(blank=True, default='00094238B6', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='irtaxid',
            field=models.CharField(blank=True, default='0000000000000000000000', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='taxid',
            field=models.CharField(blank=True, default='A16G7G04C4800094238B64', max_length=255, null=True),
        ),
    ]
