# Generated by Django 4.1.7 on 2023-07-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_bill_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='error',
            field=models.CharField(max_length=2555, null=True),
        ),
    ]
